### ISSUE TITLE
Airboost/Jetboost

### ISSUE THREAD

**Issue by Yudouwoodou** [RamenNoodles452/ProjectStealth#65] opened 2019-01-21 17:53 UTC
The dodge button for rapid momentum on the ground should have a similar effect in the air. I do want to keep the cadence of hold -> dash -> hold -> dash with the Jetboost upgrade. Right now the dodge button and movement are done with the same hand, LB + Dpad/Stick and the input stringing with the same hand can get awkward compared to alternating between the jump button and dpad

so my solution is thus:

- [x] we keep the input for airhold and boost the same. jump button in the air, and then press a direction while in airhold (currently locked to 8 directions. No 360 aim)
- [x] the dash itself gives invincibility while using it.
- [x] the dodge button in the air is a shortcut for the airboost without having to go into airhold.

**Comment by JesterInBlack** [comment] 2019-01-22 01:23
Duplicate of #58 , with some clarification on the double input mapping.

**Closed as completed** 2019-01-22 03:48 UTC
Labels: Duplicate, New Feature
