### ISSUE TITLE
Wall climb adjustments

### ISSUE THREAD

**Issue by Yudouwoodou** [RamenNoodles452/ProjectStealth#55] opened 2019-01-18 20:33 UTC
Auto transitioning from wall to ground feels really weird.

- [x] Change this so that Val stops at the ledge when climbing up a wall

transitions where Val is "sliding" from one surface to another uses no jump inputs
fallthrough climbables
- [ ] > up: go from climbing under them to crouching on top of them
top of wall
- [x] > into wall: go from climbing wall to on the ground next to wall
edge of platform
- [x] > down: crouch then to the wall
bottom of wall
- [x] >down: slide down till you touch ground and stand

Transitions where Val is letting go of said surface require direction + jump
fallthrough climbables + Ceiling
- [x] > down + jump to drop down
wall
- [x] > down + jump to drop down
- [x] > away from wall + jump to leap off of it

**Comment by JesterInBlack** [comment] 2019-01-19 08:30
Changed jump neutral to in toward the wall. Can revisit if it doesn't work out.

**Comment by JesterInBlack** [comment] 2019-01-20 22:17
on top of fallthrough ceiling
- [ ] down + jump to climb under it.

**Comment by JesterInBlack** [comment] 2019-01-21 11:54
The fallthrough components of this are a duplicate of issue #60 . Closing.

**Closed as completed by JesterInBlack** 2019-01-21 11:54 UTC
Labels: Duplicate, Enhancement
